---
collections:
  # - name: ansible.platform
  - name: ansible.hub
  # - name: ansible.controller
  - name: awx.awx
  - name: ansible.eda
  - name: infra.aap_configuration
#  - name: infra.aap_configuration_extended
