---
collections:
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
  - name: infra.aap_configuration
#  - name: infra.aap_configuration_extended
  - name: infra.aap_utilities  
  - name: containers.podman # required for infra.ee_utilities
  - name: infra.ee_utilities
