---
- name: Configure AAP
  hosts: localhost
  vars:
    aap_validate_certs: false
    # Variables moved to secret_vars file:
    # aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    # aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    # aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"

  pre_tasks:
    - name: Include credentials from file
      ansible.builtin.include_vars:
        file: ./secret_vars
      no_log: true

    - name: Include AAP configuration variables
      ansible.builtin.include_vars:
        dir: ./aap_configuration

  roles:
    - infra.aap_configuration.dispatch
