---
- name: Export AAP configuration
  hosts: localhost

  tasks:
    - name: Include credentials from file
      ansible.builtin.include_vars:
        file: ./secret_vars
      no_log: true

    # - name: Export configuration
    #   ansible.controller.export:
    #     controller_username: "{{ aap_username }}"
    #     controller_password: "{{ aap_password }}"
    #     controller_host: "{{ aap_hostname }}"
    #     validate_certs: false
    #     all: true
        # workflow_job_templates: "F5 BIG IP - configure infrastructure"


    - name: Add user
      ansible.controller.user:
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        controller_host: "{{ aap_hostname }}"
        # validate_certs: false
        username: jdoe10
        password: foobarbaz
        email: jdoe@example.org
        organization: Default
        state: present
