---
controller_execution_environments:
  - name: ee-arista-avd
    image: aap.rh.lab/ee-arista-avd:1.0
    organization: Default
    pull: missing

  - name: ee-network-checkpoint
    image: aap.rh.lab/ee-network-checkpoint:1.0
    organization: Default
    pull: missing

  - name: ee-network-aci
    image: aap.rh.lab/ee-network-aci:1.0
    organization: null
    pull: missing

  - name: ee-panos
    image: aap.rh.lab/ee-panos:1.4
    organization: null
    pull: missing

  - name: ee-network
    image: aap.rh.lab/ee-network:1.8
    organization: null
    pull: missing

  - name: ansible-automation-platform-25/ee-supported-rhel8
    image: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest
    organization: null
    pull: missing
    credential: registry.redhat.io

  - name: ansible-automation-platform-25/ee-supported-rhel9
    image: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9:latest
    organization: null
    pull: missing
    credential: registry.redhat.io


  - name: ansible-automation-platform-25/ee-minimal-rhel8
    image: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest
    organization: null
    pull: ''
