---
controller_execution_environments:
  - name: "Hub Minimal execution environment"
    image: "aap.rh.lab/ee-minimal-rhel8:latest"
    pull: ""

  - name: "Hub Default execution environment"
    image: "aap.rh.lab/ee-supported-rhel8:latest"
    pull: ""

  - name: "Minimal execution environment"
    image: "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest"
    pull: ""

  - name: "Default execution environment"
    image: "registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest"
    pull: ""

  - name: "Control Plane Execution Environment"
    image: "registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest"
    pull: ""

  - name: "ee-network"
    image: "aap.rh.lab/ee-network:1.8"
    pull: "missing"

  - name: "ee-panos"
    image: "aap.rh.lab/ee-panos:1.4"
    pull: "missing"
 
  - name: "ee-network-aci"
    image: "aap.rh.lab/ee-network-aci:1.0"
    pull: "missing"