---
gateway_settings:
  gateway_token_name: "X-DAB-JW-TOKEN"
  gateway_access_token_expiration: "600"
  jwt_expiration_buffer_in_seconds: "2"
  gateway_basic_auth_enabled: "true"
  gateway_proxy_url: "https://aap.rh.lab:443"
  gateway_proxy_url_ignore_cert: "false"
  jwt_private_key: "$encrypted$"
  status_endpoint_backend_timeout_seconds: "5"
  status_endpoint_backend_verify: "true"
  resource_client_request_timeout: "2.0"
  request_timeout: "30"
  password_min_length: "0"
  password_min_digits: "0"
  password_min_upper: "0"
  password_min_special: "0"
  allow_admins_to_set_insecure: "false"
  LOGIN_REDIRECT_OVERRIDE: ""
  custom_login_info: ""
  custom_logo: ""
  SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL: "false"
  SESSION_COOKIE_AGE: "900"
  DEFAULT_PAGE_SIZE: "50"
  MAX_PAGE_SIZE: "200"
  ALLOW_OAUTH2_FOR_EXTERNAL_USERS: "false"
  CONTROLLER_SSO_URL: ""
  AUTOMATION_HUB_SSO_URL: ""
  INSIGHTS_TRACKING_STATE: "true"
  RED_HAT_CONSOLE_URL: "https://console.redhat.com"
  REDHAT_USERNAME: ""
  REDHAT_PASSWORD: "$encrypted$"
  SUBSCRIPTIONS_USERNAME: ""
  SUBSCRIPTIONS_PASSWORD: "$encrypted$"
  AUTOMATION_ANALYTICS_GATHER_INTERVAL: "14400"

